services:
  app:
    build:  
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"